### ISSUE TITLE
MachObfuscator obfuscates dynamic property selectors

### ISSUE THREAD

**Issue by shizu2014** [kam800/MachObfuscator#10]
I found that he does not filter the system's functions and class name methods.
What other settings do you need to do?

**Comment by kam800** [comment]
Can you tell what methods and classes exactly? Does it result in a crash?

**Comment by shizu2014** [comment]
https://github.com/Polidea/ios-class-guard
You can look at how to implement the filtering system class and system method in this open source library.

**Comment by kam800** [comment]
The MachObfuscator filters system class names and methods. It does the filtering a different way from ios-class-guard, because it does not operate on source code. MachObfuscator works great on our example apps. I think you hit some corner case, or latest Xcode changed the mach-o structure a bit. I am very curious about this problem. Could you please give a little more information? Which system class names were not filtered?

**Comment by shizu2014** [comment]
![QQ20190314-180832](https://user-images.githubusercontent.com/10099006/54348546-388e7b80-4684-11e9-8dfe-8e1b3434adfc.png)
many className

**Comment by kam800** [comment]
Thanks for the screenshots. Now I am able to reason about that case :)

Those replacements seem to be perfectly ok.
✅ `AppDelegate` → This seems to be your `UIApplicationDelegate` implementation, this symbol can be obfuscated without any problem.
✅ `UIApplicationDelegate` → It is system protocol, but it is not referenced by any of the system libraries. `UIKitCore` references `application:didFinishLaunching:` and other `application:*` methods, but it doesn't have any reference to `UIApplicationDelegate`. `UIApplicationDelegate` is being compiled into the app. If fact `UIApplicationDelegate` is not needed in runtime at all (try removing `UIApplicationDelegate` conformance and running the app).
✅ `FBSDK*` → This seems to be Facebook SDK symbols, not system symbols. MachObfuscator will attempt to obfuscate everything inside the app bundle (including 3rd party libraries). This is a big advantage on MachObfuscator – other obfuscators can't do that. Does obfuscation break Facebook SDK? If so, currently there is no exclusion mechanism, but I have a plan to add it later.
✅ `WKScriptMessageHandler` → same story as `UIApplicationDelegate`.

I you would like to learn more about the MachObfuscator obfuscation, please watch this [0xFEEDFACE](https://youtu.be/OsVXKvMhFi0?t=1628) video (27:08-33:04).

Anyway. Does you app fail to run after the obfuscation?

**Comment by shizu2014** [comment]
对的 无法运行

**Comment by shizu2014** [comment]
correct
Can not run

**Comment by kam800** [comment]
Unfortunatelly, MachObfuscator requires some expert knowledge :( I have to ask if you performed additional steps:
- did you resign the whole app? (https://github.com/kam800/MachObfuscator/blob/master/resign.sh)
- does your app useCoreData?

Sory for that. I am going to add automatic resigning as soon as possible, for now resigning needs to be performed with the script. CoreData is currently unsupported, but we are also going to support CoreData (by obfuscation or exclusion).

If your app still doesn’t work, we could investigate more. Thanks again for your report, together we can make MachObfuscator better :)

**Comment by shizu2014** [comment]
I can send your mail to your program. Look, what is your email address?

**Comment by shizu2014** [comment]
I can send your mail to your program. Look, what is your email address?
no coreData
already resign

**Comment by kam800** [comment]
Could you please send your email adress to my temporary mailbox ‘zvb@www.barryogorman.com’? I will contact you from my real address then. (don’t want to post my address on the Internet).

**Comment by kam800** [comment]
I changed 3 things:
- MachObfuscator ignores `@dynamic` Obj-C properties (this fixes `GVUserDefaults`).
- MachObfuscator uses `__cstrings` section to detect dynamically loaded libraries (this fixes `AdSupport` dynamic loading).
- MachObfuscator uses `__cstrings` as additional source for blacklisting (this fixes the watchdog kill).
I will improve those mechanisms further in the future.

It seems like your app used a lot of Obj-C runtime – this caused all these problems. I tried obfuscating the app – the app seems to work now. Can you retest the obfuscation using latest MachObfuscator version?

**Comment by linhmui** [comment]
Thanks for your help. But with the latest build. My game "bike" can't run
success with Obfuscator, with second game "Zombie" can run success but when
re-sign and install in my device it still crash. Result same older version
Can you send me the latest built Binary file of your project which you run
successfully and re-sign work in real device?

*Run with "bike" game:*
[image: image.png]
*Try another run:*
[image: image.png]

Thanks
