### ISSUE TITLE
Failed when build with Xcode

### ISSUE THREAD

**Issue by linhmui** [kam800/MachObfuscator#11]
Dear
When build with xcode, i show "Build Failed"

> /Users/LinhMui/Library/Developer/Xcode/DerivedData/MachObfuscator-hiuiglqeupyhqzfaqyqbkxxmzanu/Build/Intermediates.noindex/MachObfuscator.build/Debug/MachObfuscator.build/Script-D481608B211CF068008671D8.sh: line 2: swiftformat: command not found
Command /bin/sh failed with exit code 127

![Screenshot_1](https://user-images.githubusercontent.com/18011987/55377643-1039c480-5540-11e9-9450-b9b7fbaf169c.png)

Please help me or sent me binary file when built complete
Thanks

**Comment by kam800** [comment]
Hi. Thanks for report. I should make `swiftformat` optional. Until then, could you please just remove the `swiftformat` build phase?
![Screenshot 2019-04-02 at 11 01 30](https://user-images.githubusercontent.com/2962788/55390126-d7e1b880-5536-11e9-953f-115dd3c9151e.png)

**Comment by linhmui** [comment]
Thanks for quick support. But i get more error when remove this script as you show
![Screenshot_1](https://user-images.githubusercontent.com/18011987/55391176-037a9800-5563-11e9-9df0-e695917ee6f6.png)

**Comment by kam800** [comment]
Hmm. What Xcode version do you have?

**Comment by linhmui** [comment]
Dear
I’m using xcode 9. Please help

Thanks

**Comment by kam800** [comment]
MachObfuscator requires Swift 4.2, so Xcode 10 is needed. I am wondering... maybe I should provide MachObfuscator in homebrew. What do you think?
Until then, could you please download Xcode 10 and compile the MachObfuscator yourself? I will try to add this to homebrew, but I won't do this today.

**Comment by linhmui** [comment]
Thanks master

**Comment by linhmui** [comment]
Dear 
I have other issue when built complete with xcode 10. Please check this error:

> MacBook-Air:~ lion$ /Users/lion/Downloads/MachObfuscator -v /Users/lion/Downloads/Payload/surfing.app 
Will obfuscate file:///Users/lion/Downloads/Payload/surfing.app/
Looking for dependencies...
WARN: Unable to resolve dylib path /System/Library/PrivateFrameworks/WebKit.framework/WebKit
WARN: Unable to resolve dylib path /usr/lib/system/libsystem_kernel.dylib
WARN: Unable to resolve dylib path /usr/lib/system/libsystem_platform.dylib
WARN: Unable to resolve dylib path /usr/lib/system/libsystem_pthread.dylib
WARN: Unable to resolve dylib path /usr/lib/system/libsystem_platform.dylib
WARN: Unable to resolve dylib path /usr/lib/system/libsystem_platform.dylib
WARN: Unable to resolve dylib path /usr/lib/system/libsystem_platform.dylib
WARN: Unable to resolve dylib path /usr/lib/system/libsystem_platform.dylib
WARN: Unable to resolve dylib path /usr/lib/system/libsystem_platform.dylib
1 obfuscable images
2 obfuscable NIBs
Collecting symbols...
8892 obfuscable selectors
1347 obfuscable classes
1268280 unobfuscable selectors
461766 unobfuscable classes
Mangling symbols...
8711 mangled selectors
1333 mangled classes
Obfuscating file:///Users/lion/Downloads/Payload/surfing.app/surfing
Precondition failed: file /Users/lion/Downloads/MachObfuscator-master/MachObfuscator/DataAccess/Data+Mapping.swift, line 27

![Screenshot_1](https://user-images.githubusercontent.com/18011987/55464152-a9daa200-5624-11e9-93e8-1de148a23339.png)

**Comment by kam800** [comment]
Thanks for reporting this. Can you please send me the IPA file? Preferably on Twitter, my account: `@kam800`. Having the IPA, I will be able to fix the issue.

**Comment by linhmui** [comment]
Dear Master
Please check message, thanks
