### ISSUE TITLE
MachObfuscator crashes

### ISSUE THREAD

**Issue by Chinyaev** [kam800/MachObfuscator#13]
Hi!

I builded MachObufscator and SimpleMacApp, then copy them in folder
Running terminal and wrote ./MachObfuscator -v SimpleMacApp.app/
But nothing happened (obfuscation I mean)

Will obfuscate file:///Users/pavel/Documents/MachObfuscator/SimpleMacApp.app
Looking for dependencies...
0 obfuscable images
0 obfuscable NIBs
Collecting symbols...
0 obfuscable selectors
0 obfuscable classes
0 unobfuscable selectors
0 unobfuscable classes
Mangling symbols...
0 mangled selectors
0 mangled classes
Saving all the files in place...
BYE
MacBook-Pro-Pavel:MachObfuscator pavel$ 

What I made wrong?

**Comment by linhmui** [comment]
Create new folder and place file want to run Obfuscation and run
./MachOfuscator/newfolder

**Comment by Chinyaev** [comment]
> Create new folder and place file want to run Obfuscation and run
> ./MachOfuscator/newfolder

Thank your for answer. But now i get error Illegal instruction: 4

```
MacBook-Pro:MachObfuscator pavel$ ./MachObfuscator -v ./out/SampleMacApp.app
Will obfuscate file:///Users/pavel/Documents/MachObfuscator/out/SampleMacApp.app/
Looking for dependencies...
Illegal instruction: 4
```

**Comment by linhmui** [comment]
You can try this 
`./MachObfuscator -v ./out`
with SampleMacApp.app in "out" folder

**Comment by Chinyaev** [comment]
Doesn't work too..
Looking for dependencies...
Illegal instruction: 4
My Xcode version 10.2, Mac 10.14.4

linhmui, can you send me your binary MachObfuscator please? My email chinyaevpavel@gmail.com

**Comment by kam800** [comment]
Hi. What Xcode version did you use? Would you be pleased to see MachObfuscator binary available on github?

**Comment by Chinyaev** [comment]
> Hi. What Xcode version did you use? Would you be pleased to see MachObfuscator binary available on github?
Hi! My Xcode version 10.2, Mac 10.14.4. Yea, I will pleased, maybe it will work

**Comment by kam800** [comment]
Two PRs opened. I wonder if `swift5` branch fixes the crash.

**Comment by kam800** [comment]
@Chinyaev can you confirm, the issue was fixed?

**Comment by Chinyaev** [comment]
> @Chinyaev can you confirm, the issue was fixed?
Unfortunately not. But maybe I'm doing something wrong.

**Comment by kam800** [comment]
@Chinyaev 
Can you please send me your IPA? Preferably on twitter: @kam800.
