### ISSUE TITLE
Can't show Unity Ads after using MachOfuscator

### ISSUE THREAD

**Issue by linhmui** [kam800/MachObfuscator#33]
Dear
My game can't show Unity Ads after using MachOfuscator. Please give quick fix. Because i don't check it before submit to Apple Store, now when submit and run campaign to boost install, i got no revenue so check game again and see that. Hope you can fix only today
![Screenshot_1](https://user-images.githubusercontent.com/18011987/59737216-ef535680-9286-11e9-80f7-601c90b588df.png)

Thanks

**Comment by kam800** [comment]
I have added a new `skip-symbols-from-sources` option on this branch: https://github.com/kam800/MachObfuscator/tree/blacklisting-with-sources. You can use this option to blacklist all the UnityAds symbols. 
`MachObfuscator -skip-symbols-from-sources /path/to/unity/ads/sources ...`

**Comment by linhmui** [comment]
Thanks. I will be try now
