### ISSUE TITLE
Re-signing run crash

### ISSUE THREAD

**Issue by SunnyLinSD** [kam800/MachObfuscator#36]
Dear,
  Thank you for the tools provided. When I crash after using it, like this: 

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000020
VM Region Info: 0x20 is not in any region.  Bytes before following region: 4328620000
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                 0000000102018000-0000000102198000 [ 1536K] r-x/r-x SM=COW  ...pp/appName

How can I solve this problem?

**Comment by kam800** [comment]
I don’t fully understand. Does your app crash after signing, or does the signing process itself?
