### ISSUE TITLE
Some methods will be deleted

### ISSUE THREAD

**Issue by Ade0408** [kam800/MachObfuscator#37]
Dear
When I use `MachObfuscator -v MyApp.app`, I found that some method names are missing in __objc_methname, like this: 

before:
![image](https://user-images.githubusercontent.com/11570519/60242808-3bd30d80-98e9-11e9-909a-109c72654048.png)
![image](https://user-images.githubusercontent.com/11570519/60243160-2c07f900-98ea-11e9-908d-84350e5c5266.png)

after:
![image](https://user-images.githubusercontent.com/11570519/60242939-b2700b00-98e9-11e9-9eea-15128030491f.png)
![image](https://user-images.githubusercontent.com/11570519/60243177-32967080-98ea-11e9-9e50-3e69e04212c5.png)

`initData::` and `login::` is miss, I can't find what caused it.
I hope you can help me solve, Thanks

**Comment by kam800** [comment]
Could you please send me the IPA? Preferably on Twitter @kam800.

**Comment by SunnyLinSD** [comment]
Can you give me your email? I don't use Twitter.

**Comment by kam800** [comment]
As discussed on Twitter - this is how the tool works :)
