### ISSUE TITLE
Erase assert/fatalError file paths

### ISSUE THREAD

**Issue by kjamroz-bt** [kam800/MachObfuscator#45]
`__cstring` section contain filenames that are generated by `#file` (in Swift) or `__FILE__` (C/C++/ObjC)
In particular they appear when using `fatalError` in Swift.
They are stored in binary near class names, so they should be deleted to not give original class name this way.

It is hard to detect them, so patten (prefix) to recognize them must be given as parameter.

**Comment by kam800** [comment]
Great use case! I will be very happy to merge that:)
