### ISSUE TITLE
Add option to replace arbitrary cstrings

### ISSUE THREAD

**Issue by kjamroz-bt** [kam800/MachObfuscator#46]
Add option to replace arbitrary cstrings. This is a bit dangerous, but sometimes useful, for example if there is a text that should be obfuscated but is not a symbol.

**Comment by kjamroz-bt** [comment]
My current use case for this feature in testing is to replace a static text on one of the application controls so I can check if I am running obfuscated application or not.

**Comment by pbogdan-bt** [comment]
Command line arguments parser expects `--replace-with`, whereas manual and all concerning error say `--replace-cstring-with`
