### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ZuoCaiSong** [kam800/MachObfuscator#52]
can You add some code comment ? On the principle of Obfuscator, I do not understand ,thank you

**Comment by kam800** [comment]
Hi, the MachObfuscator codebase is large. It would be hard to add comments everywhere.
I have two questions:
1) Are you familiar with Mach-O file format?
2) What exactly don't you understand?

Will be glad to help you with the MachObfuscator.

**Comment by kam800** [comment]
Take a look at [README](https://github.com/kam800/MachObfuscator#under-the-hood-) please. If you have any questions – feel free to ask at twitter `@kam800`.
