### ISSUE TITLE
WARN: Unable to resolve dylib path /System/Library/Frameworks/XXX

### ISSUE THREAD

**Issue by ZuoCaiSong** [kam800/MachObfuscator#53]
Looking for dependencies...
WARN: Unable to resolve dylib path /System/Library/Frameworks/CoreMotion.framework/CoreMotion
WARN: Unable to resolve dylib path /usr/lib/libSystem.B.dylib
WARN: Unable to resolve dylib path /System/Library/Frameworks/MediaToolbox.framework/MediaToolbox
WARN: Unable to resolve dylib path /System/Library/Frameworks/CoreText.framework/CoreText
WARN: Unable to resolve dylib path /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox
WARN: Unable to resolve dylib path /System/Library/Frameworks/AVFoundation.framework/AVFoundation
WARN: Unable to resolve dylib path /System/Library/Frameworks/CFNetwork.framework/CFNetwork
WARN: Unable to resolve dylib path /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics
WARN: Unable to resolve dylib path /System/Library/Frameworks/CoreLocation.framework/CoreLocation
WARN: Unable to resolve dylib path /System/Library/Frameworks/CoreMedia.framework/CoreMedia
WARN: Unable to resolve dylib path /System/Library/Frameworks/CoreVideo.framework/CoreVideo
WARN: Unable to resolve dylib path /System/Library/Frameworks/Foundation.framework/Foundation
WARN: Unable to resolve dylib path /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
WARN: Unable to resolve dylib path /System/Library/Frameworks/OpenAL.framework/OpenAL
WARN: Unable to resolve dylib path /System/Library/Frameworks/OpenGLES.framework/OpenGLES
WARN: Unable to resolve dylib path /System/Library/Frameworks/QuartzCore.framework/QuartzCore
WARN: Unable to resolve dylib path /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
WARN: Unable to resolve dylib path /System/Library/Frameworks/UIKit.framework/UIKit
WARN: Unable to resolve dylib path /usr/lib/libiconv.2.dylib
WARN: Unable to resolve dylib path /System/Library/Frameworks/Metal.framework/Metal
WARN: Unable to resolve dylib path /System/Library/Frameworks/GameController.framework/GameController
WARN: Unable to resolve dylib path /System/Library/Frameworks/Security.framework/Security
WARN: Unable to resolve dylib path /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
WARN: Unable to resolve dylib path /usr/lib/libicucore.A.dylib
WARN: Unable to resolve dylib path /System/Library/Frameworks/AdSupport.framework/AdSupport
WARN: Unable to resolve dylib path /System/Library/Frameworks/CoreImage.framework/CoreImage
WARN: Unable to resolve dylib path /System/Library/Frameworks/WebKit.framework/WebKit
WARN: Unable to resolve dylib path /System/Library/Frameworks/AssetsLibrary.framework/AssetsLibrary
WARN: Unable to resolve dylib path /System/Library/Frameworks/StoreKit.framework/StoreKit
WARN: Unable to resolve dylib path /usr/lib/libz.1.dylib
WARN: Unable to resolve dylib path /System/Library/Frameworks/Photos.framework/Photos
WARN: Unable to resolve dylib path /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
WARN: Unable to resolve dylib path /usr/lib/libsqlite3.dylib
WARN: Unable to resolve dylib path /usr/lib/libobjc.A.dylib
WARN: Unable to resolve dylib path /usr/lib/libc++.1.dylib
WARN: Unable to resolve dylib path /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation

**Comment by kam800** [comment]
Could you please provide more details? What happens afterwards? Does your app work, or just crashes? Does the app become obfuscated? Is it the Mac app or the iOS app? What Xcode version did you use to compile it? Is there anything special about the app, I should know?

**Comment by ZuoCaiSong** [comment]
can't read systeom methon , so it will cause the iOS  App to crash , The Xcode current version is 11.0 beta4 . does not exist the path "/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot"  in my Mac.
my Mac  current version is 10.15 Beta (19A512f)

Not very knowledgeable about  Mach-O file format , so not modify  Mach-O file

**Comment by kam800** [comment]
MachObfuscator wasn't tested for Xcode 11 yet. If this is an Xcode 11 issue – we will for sure take a look at it. Until then, please use Xcode 10 to build your app.

**Comment by HuaZao** [comment]
Xcode11 iosRuntimeRoot path changes to `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot`
