### ISSUE TITLE
Invalid input options

### ISSUE THREAD

**Issue by KukrCZ** [kam800/MachObfuscator#82]
Hello,

I tried to use your project and discovered that there is no "--swift-obfuscation" option.

I've been using this line of code:
`sh("MACH_OBFUSCATOR=../MachObfuscator ../obfuscate.sh ../exported_ipa/#{TARGET_NAME}.ipa NO_RESIGN -v --swift-obfuscation | tee ../app/obfuscation.log")`

Any kind of help would be highly appreciated.

Thanks.

**Comment by kam800** [comment]
Hi. Thanks for your report. You are right. There is no `--swift-obfuscation`. Could you please change it to `--swift-reflection` on your side? We will update the script. Sorry for that.
