### ISSUE TITLE
Ironsrc ads SDK break after using MachOfuscator

### ISSUE THREAD

**Issue by linhmui** [kam800/MachObfuscator#89]
Dear
I using Ironsource Ads to monetize but when i using MachOfuscator, it break my ads. I try to using skip framework but nothings happen. You can see Ironsrc SDK here: https://developers.ironsrc.com/ironsource-mobile/ios/ios-sdk/#step-1
Please help me
Thanks

**Comment by kam800** [comment]
Let me reopen that issue until the changes are merged into a `master` branch.
