### ISSUE TITLE
IPA file does not contain SwiftSupport directory

### ISSUE THREAD

**Issue by kondratk** [kam800/MachObfuscator#95]
AppStore rejects our build due to missing SwiftSupport folder inside IPA file. 
After analyzing source and target ipa files, the source one contains SwiftSupport folder, while obfuscated one does not.

Error message from AppStoreConnect:
```ITMS-90426: Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.```

![image](https://user-images.githubusercontent.com/6077388/69144984-dd434180-0acc-11ea-893c-4c2af0aa7a27.png)

Of course, unobfuscated app goes through AppStoreConnect without any issues.

**Comment by kam800** [comment]
Hi. Sorry for answering late. Could you tell me what was the reason? Did you find the solution?
